
server:
  port: 8084
spring:
  servlet:
    multipart:
      max-file-size: 22MB
      max-request-size: 22MB
  application:
    name: forum_review
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    username: keycloak
    url: jdbc:mysql://localhost:3306/keycloak?useSSL=false&serverTimezone=UTC
    hikari:
      maximumPoolSize: 20
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: simone
  bearer-only: true
  resource: login-app
role:
  default:
    name: superAdmin
  admin:
    name: admin
  partner:
    name: user